name: Docker Image CI

on: push
#
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # may be actions/checkout@v2 now
      - name: Login to DockerHub Registry # use Dockerfile to build an image to push to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} |  docker login -u ${{ secrets.javascr1p7 }} --password-Javascript0
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        run: docker build -t javascr1p7/dockerimage .
      - name: Push the tagged Docker image
        run: docker push javascr1p7/dockerimage
# npm install; then npm test
